In [15]:
import pandas as pd

In [37]:
data = {
    'Name' : ['Ahmad', 'Ali', 'Hassan'],
    'Degree' : ['BSCS', 'BSIT', 'BSSE']
}

In [38]:
df = pd.DataFrame(data)

In [40]:
df.head(2)

    Name Degree
0  Ahmad   BSCS
1    Ali   BSIT

In [44]:
df.rename(columns={'Degree' : 'Class'}, inplace=True)

In [45]:
df

     Name Class
0   Ahmad  BSCS
1     Ali  BSIT
2  Hassan  BSSE

In [49]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      str
 1   Class   3 non-null      str
dtypes: str(2)
memory usage: 180.0 bytes

In [50]:
df.describe()

         Name Class
count       3     3
unique      3     3
top     Ahmad  BSCS
freq        1     1

In [52]:
df.to_csv('Student.csv', index=False)