In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('Student.csv')

In [4]:
df

     Name Class
0   Ahmad  BSCS
1     Ali  BSIT
2  Hassan  BSSE

In [ ]:
df.loc[df.Name=='Ali'] #it will select particular row

  Name Class
1  Ali  BSIT

In [7]:
df[['Name']] #it will select a column

     Name
0   Ahmad
1     Ali
2  Hassan